### PR TITLE
Fixed Spelling Mistakes

### PR DESCRIPTION
**Pull request by samcodee**
There were some spelling mistakes. I fixed it

### CODE REVIEW

**Comment by CH-Tamilzha** [comment]
Thank you

**Comment by CH-Tamilzha** [comment]
> 
> 
> Thank you

**Review by electricthoughts — COMMENTED** [review]
Thank you!

:)

**Comment by electricthoughts** [comment]
Hey, apparently this is a 'closed pull request' and I really don't know what it is, I new to Github, there is not merge option coming for this even though I reviewed it...

**Comment by samcodee** [comment]
> Hey, apparently this is a 'closed pull request' and I really don't know what it is, I new to Github, there is not merge option coming for this even though I reviewed it...

### Pull request means, if you have a big code-base say, for example, you have developed the world's biggest and greatest app, became famous, and you started the company. You have made the code open-source. Now you one person cannot find all the issues, bugs, etc. If an another person finds a bug, you can ask them to report it through the issues tab of the repo. 

### Then a person who knows to fix a bug can create a clone of this repo by forking it and then fixing it and then creating a pull request. The owner of the repo, (that is you) can review it and merge their code into the main codebase and close the pull request (meaning that the code has been merged. The same goes to issues after it has been fixed, you can close that)

### I just closed the pull request without knowing. So, you were not able to merge it.

This is my understanding of PRs

**Comment by electricthoughts** [comment]
> Pull request means, if you have a big code-base say, for example, you have developed the world's biggest and greatest app, became famous, and you started the company. You have made the code open-source. Now you one person cannot find all the issues, bugs, etc. If an another person finds a bug, you can ask them to report it through the issues tab of the repo...

Oh okay, I do know the outline of PRs, but I was confused when I wasn't able to merge it, that's why I asked you, thank you anyways.

**Comment by electricthoughts** [comment]
So, now I will be able to merge the PR only if make it open or what should I do?

**Pull request closed without merging**
